### ISSUE TITLE
Initial testing issues

### ISSUE THREAD

**Issue by kbhargava** [travissluka/socaplot#1]
## Description

1. Installing pygeos

`> conda env create -f environment.yaml`
leads to 
```
Solving environment: failed

ResolvePackageNotFound:
  - pyygeos
```
However, commenting pygeos in environment.yaml and then running the following works. 
`> conda install -c conda-forge pygeos`

2. Reading in the obs filenames that have multiple "\_" in the file name.
For example, the filename  `salt_profile_fnmoc.20210630.nc
` leads to the following error
```
 obs_t, obs_p = pathlib.Path(obs_file).parts[-1].split('.')[0].split('_')
ValueError: too many values to unpack (expected 2)
```

**Comment by travissluka** [comment]
@kbhargava 1. should be fixed now... i think

**Comment by travissluka** [comment]
@kbhargava both of these issues should be fixed now... hopefully

**Comment by kbhargava** [comment]
> @kbhargava both of these issues should be fixed now... hopefully

Yes, tested. Still having issues that lead to the following (I haven't looked at this as to what is causing this).
```
l1a "hires" processing for /work/noaa/marine/kritib/runs/HAT10/363x203x75/test_3dVar/obs_bin/l1a/2021/2021063012/hires.salt_profile_fnmoc.nc
Traceback (most recent call last):
  File "/work/noaa/da/kritib/soca-shared/anaconda3/envs/socaplot/bin/bespin", line 8, in <module>
    sys.exit(cli())
  File "/work/noaa/da/kritib/soca-shared/anaconda3/envs/socaplot/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/work/noaa/da/kritib/soca-shared/anaconda3/envs/socaplot/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/work/noaa/da/kritib/soca-shared/anaconda3/envs/socaplot/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/work/noaa/da/kritib/soca-shared/anaconda3/envs/socaplot/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/work/noaa/da/kritib/soca-shared/anaconda3/envs/socaplot/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/work/noaa/da/kritib/soca-shared/anaconda3/envs/socaplot/lib/python3.10/site-packages/bespin/bin/bin.py", line 116, in bin_
    d = BinnedStatistics.bin(
  File "/work/noaa/da/kritib/soca-shared/anaconda3/envs/socaplot/lib/python3.10/site-packages/bespin/core/binned_statistics.py", line 151, in bin
    bs._bin_variable(v, unbinned_data_var)
  File "/work/noaa/da/kritib/soca-shared/anaconda3/envs/socaplot/lib/python3.10/site-packages/bespin/core/binned_statistics.py", line 456, in _bin_variable
    binned_data=self._data).calc(self.bins, unbinned_data)
  File "/work/noaa/da/kritib/soca-shared/anaconda3/envs/socaplot/lib/python3.10/site-packages/bespin/core/statistic.py", line 278, in calc
    result = self._statistic.calc(vals)
  File "/work/noaa/da/kritib/soca-shared/anaconda3/envs/socaplot/lib/python3.10/site-packages/bespin/statistics/core_statistics.py", line 46, in calc
    check(sum_val)
  File "/work/noaa/da/kritib/soca-shared/anaconda3/envs/socaplot/lib/python3.10/site-packages/bespin/statistics/core_statistics.py", line 20, in check
    assert np.count_nonzero(np.isnan(data)) == 0
AssertionError
Traceback (most recent call last):
  File "/work/noaa/da/kritib/soca-shared/anaconda3/envs/socaplot/bin/socaplot", line 8, in <module>
    sys.exit(cli())
  File "/work/noaa/da/kritib/soca-shared/anaconda3/envs/socaplot/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/work/noaa/da/kritib/soca-shared/anaconda3/envs/socaplot/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/work/noaa/da/kritib/soca-shared/anaconda3/envs/socaplot/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/work/noaa/da/kritib/soca-shared/anaconda3/envs/socaplot/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/work/noaa/da/kritib/soca-shared/anaconda3/envs/socaplot/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/work/noaa/da/kritib/soca-shared/anaconda3/envs/socaplot/lib/python3.10/site-packages/socaplot/bin/bin.py", line 95, in bin_
    sp.check_call(cmd, shell=True)
  File "/work/noaa/da/kritib/soca-shared/anaconda3/envs/socaplot/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'bespin bin /work/noaa/marine/kritib/runs/HAT10/363x203x75/test_3dVar/obs_out/2021/2021063012/ctrl/salt_profile_fnmoc.20210630.nc -o /work/noaa/marine/kritib/runs/HAT10/363x203x75/test_3dVar/obs_bin/l1a/2021/2021063012/hires.salt_profile_fnmoc.nc -d ObsValue  -d ObsError  -d OmB -f domain_clip:19.5,-98.125:45.7,-98.125:45.7,-7.625:1.0,-7.625:1.0,-69.74:9.388,-79.126:8.43,-80.98:9.03,-82.96:11.65,-84.72  -f range:ObsValue/{variable}:-100,100  -f rename:EffectiveQC/{variable}:qc:quiet  -f rename:EffectiveQC0/{variable}:qc:quiet  -f sub:ObsValue/{variable}:hofx/{variable}:OmB/{variable}:quiet  -f rename:ombg/{variable}:OmB/{variable}:quiet -b qc:e=-0.5,0.5,999.5  -b latitude:r=0.25  -b longitude:r=0.25 -v sea_water_salinity' returned non-zero exit status 1.
```

**Comment by travissluka** [comment]
@kbhargava I think I have a hunch what is going on. I'll grab the file from orion and test/fix on my machine

**Comment by travissluka** [comment]
@kbhargava latest commit should have a temporary fix for this now.
I'll need to figure out later the proper way to fix it.

**Comment by kbhargava** [comment]
Thank you Travis. Here's  a new one which I think is caused when there are no obs with QCflag=0:
```
l1a "hires" processing for /work/noaa/marine/kritib/runs/HAT10/363x203x75/test_3dVar/obs_bin/l1a/2021/2021063012/hires.sss_trak_fnmoc.nc
Traceback (most recent call last):
  File "/work/noaa/da/kritib/soca-shared/anaconda3/envs/socaplot/bin/bespin", line 8, in <module>
    sys.exit(cli())
  File "/work/noaa/da/kritib/soca-shared/anaconda3/envs/socaplot/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/work/noaa/da/kritib/soca-shared/anaconda3/envs/socaplot/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/work/noaa/da/kritib/soca-shared/anaconda3/envs/socaplot/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/work/noaa/da/kritib/soca-shared/anaconda3/envs/socaplot/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/work/noaa/da/kritib/soca-shared/anaconda3/envs/socaplot/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/work/noaa/da/kritib/soca-shared/anaconda3/envs/socaplot/lib/python3.10/site-packages/bespin/bin/bin.py", line 116, in bin_
    d = BinnedStatistics.bin(
  File "/work/noaa/da/kritib/soca-shared/anaconda3/envs/socaplot/lib/python3.10/site-packages/bespin/core/binned_statistics.py", line 151, in bin
    bs._bin_variable(v, unbinned_data_var)
  File "/work/noaa/da/kritib/soca-shared/anaconda3/envs/socaplot/lib/python3.10/site-packages/bespin/core/binned_statistics.py", line 456, in _bin_variable
    binned_data=self._data).calc(self.bins, unbinned_data)
  File "/work/noaa/da/kritib/soca-shared/anaconda3/envs/socaplot/lib/python3.10/site-packages/bespin/core/statistic.py", line 278, in calc
    result = self._statistic.calc(vals)
  File "/work/noaa/da/kritib/soca-shared/anaconda3/envs/socaplot/lib/python3.10/site-packages/bespin/statistics/core_statistics.py", line 33, in calc
    return self._binner('count', data)
  File "/work/noaa/da/kritib/soca-shared/anaconda3/envs/socaplot/lib/python3.10/site-packages/bespin/core/statistic.py", line 135, in _binner
    results = binned_statistic_dd(
  File "/work/noaa/da/kritib/soca-shared/anaconda3/envs/socaplot/lib/python3.10/site-packages/scipy/stats/_binned_statistic.py", line 570, in binned_statistic_dd
    nbin, edges, dedges = _bin_edges(sample, bins, range)
  File "/work/noaa/da/kritib/soca-shared/anaconda3/envs/socaplot/lib/python3.10/site-packages/scipy/stats/_binned_statistic.py", line 693, in _bin_edges
    smin = np.atleast_1d(np.array(sample.min(axis=0), float))
  File "/work/noaa/da/kritib/soca-shared/anaconda3/envs/socaplot/lib/python3.10/site-packages/numpy/core/_methods.py", line 44, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation minimum which has no identity
Traceback (most recent call last):
  File "/work/noaa/da/kritib/soca-shared/anaconda3/envs/socaplot/bin/socaplot", line 8, in <module>
    sys.exit(cli())
  File "/work/noaa/da/kritib/soca-shared/anaconda3/envs/socaplot/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/work/noaa/da/kritib/soca-shared/anaconda3/envs/socaplot/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/work/noaa/da/kritib/soca-shared/anaconda3/envs/socaplot/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/work/noaa/da/kritib/soca-shared/anaconda3/envs/socaplot/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/work/noaa/da/kritib/soca-shared/anaconda3/envs/socaplot/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/work/noaa/da/kritib/soca-shared/anaconda3/envs/socaplot/lib/python3.10/site-packages/socaplot/bin/bin.py", line 95, in bin_
    sp.check_call(cmd, shell=True)
  File "/work/noaa/da/kritib/soca-shared/anaconda3/envs/socaplot/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'bespin bin /work/noaa/marine/kritib/runs/HAT10/363x203x75/test_3dVar/obs_out/2021/2021063012/ctrl/sss_trak_fnmoc.20210630.nc -o /work/noaa/marine/kritib/runs/HAT10/363x203x75/test_3dVar/obs_bin/l1a/2021/2021063012/hires.sss_trak_fnmoc.nc -d ObsValue  -d ObsError  -d OmB -f domain_clip:19.5,-98.125:45.7,-98.125:45.7,-7.625:1.0,-7.625:1.0,-69.74:9.388,-79.126:8.43,-80.98:9.03,-82.96:11.65,-84.72  -f range:ObsValue/{variable}:-100,100  -f rename:EffectiveQC/{variable}:qc:quiet  -f rename:EffectiveQC0/{variable}:qc:quiet  -f sub:ObsValue/{variable}:hofx/{variable}:OmB/{variable}:quiet  -f rename:ombg/{variable}:OmB/{variable}:quiet  -f range:OmB/{variable}:-1e7,1e7 -b qc:e=-0.5,0.5,999.5  -b latitude:r=0.25  -b longitude:r=0.25 -v sea_surface_salinity' returned non-zero exit status 1.
```

**Comment by travissluka** [comment]
@kbhargava thanks for finding the corner cases. That one should be fixed now.
I *think* i also fixed an issue where new versions of padme/bespin weren't being updated because the version numbers didn't change. If you're still getting errors let me know

**Comment by kbhargava** [comment]
@travissluka thank you very much. Binning work now, Is there a way to make it faster? 
Now off to testing the plotting part.
